--- 
abstract: The great new WWW::PivotalTracker!
author: 
  - Jacob Helwig <jhelwig@cpan.org>
build_requires: 
  Test::Class: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-PivotalTracker
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::Any: 0
  File::HomeDir: 0
  Getopt::Long::Descriptive: 0
  HTTP::Request: 0
  Hash::Merge: 0
  LWP::UserAgent: 0
  Perl6::Parameters: 0
  Pod::Usage: 0
  XML::Simple: 0
  parent: 0
version: !!perl/hash:version 
  alpha: 1
  original: 0.1.0_2
  qv: 1
  version: 
    - 0
    - 1
    - 0
    - 2
